### ISSUE TITLE
Error expression comma

### ISSUE THREAD

**Issue by lobor** [ngutils/cr-acl#1]
Hi, an error appear when used cr-granted="ROLE_ADMIN,ROLE_USER"
=> Error: [$parse:syntax] Syntax Error: Token ',' is an unexpected token at column 10 of the expression [ROLE_USER,ROLE_ADMIN] starting at [,ROLE_ADMIN].
I found the problem, is scope.$watch at line 112. When comment, no problem.

And not hierarchy with

``` javascript
crAcl.setInheritanceRoles({
            "ROLE_TEST" : ["ROLE_USER","ROLE_GUEST"],
            "ROLE_ADMIN" : [ "ROLE_TEST"]
        });
```

I should add ROLE_TEST and ROLE_ADMIN for this work

**Comment by gianarb** [comment]
In this moment cr-granted not support two roles
