### ISSUE TITLE
Error call function setRedirct 

### ISSUE THREAD

**Issue by BarkatiMohamed** [ngutils/cr-acl#3]
Hi 
in  your documention when you want to defined a state for authorized you said you write : crAcl.setRedirct("unauth"); the correct function is crAcl.setRedirect('unauthorized');

**Comment by gianarb** [comment]
Hi! Are you sure?
unauthorized is default value of redirect but you can replace it with your route name if you call setRedirect function..

This is the idea :P

**Comment by BarkatiMohamed** [comment]
Hi 
you miss-understood my previous msg, what Im trying to say is there is a spelling mistake (syntax) in the  crAcl.setRedirct("unauth"); it's missing an 'e' as in Redir'e'ct. this shoulb recfied in the documentation.
thanks and best regards,
