### ISSUE TITLE
Reload Page lose crAcl-Role

### ISSUE THREAD

**Issue by scne** [ngutils/cr-acl#6]
When I reload page crAcl lose setting role beacuse every time provider own is called and into it there is this
`var self = {};`

**Comment by gmittica** [comment]
Hi,

it's not an issue: you should use a session manager to store the role. We suggest [crSession](https://github.com/ngutils/cr-session) to do that , or for more complex scenario [crIdentity](https://github.com/ngutils/cr-identity)
